<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\fogo\" />
    <Folder Include="wwwroot\img\agua\" />
    <Folder Include="wwwroot\img\eletrico\" />
  </ItemGroup>

</Project>
